# Generated by Django 3.1 on 2022-05-25 15:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
