# Generated by Django 3.1 on 2022-09-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pictures',
            new_name='profile_picture',
        ),
    ]
