# Generated by Django 3.1 on 2022-05-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_name',
            new_name='product',
        ),
    ]
